### ISSUE TITLE
First initial steps working ok

### ISSUE THREAD

**Issue by palmtreefrb** [tve/mqboard#15] opened 2020-06-22 18:07 UTC
Just wanted to leave a quick note. Following your instructions and running the initial test it appears to be working. Only thing I had to do was (manually) add mqtt user and password to engine.py
self._mqclient.username_pw_set("xxxuserxxx", "xxxxpasswordxxxx")

I will play with your blinky demo next.

$ ./mqboard/mqboard.py --server mqtt.xxxxxxx.com --port 8883 --tls --prefix xxxxxxxx eval '45+876'
921
$ ./mqboard/mqboard.py --server mqtt.xxxxxxx.com --port 8883 --tls --prefix xxxxxxxx eval 'import sys; print(sys.implementation)'
(name='micropython', version=(1, 12, 0), mpy=10757)

![image](https://user-images.githubusercontent.com/7799495/85331448-fe1cac80-b48a-11ea-9e33-910d3d02fb7c.png)

**Comment by tve** [comment] 2020-06-23 20:22
I'll keep this open as a reminder to add some auth params in mqboard, thanks for the confirmation.

**Comment by tialm** [comment] 2020-07-01 18:34
Aaah this was what I was missing... Thank you! It was always going into Timeout. User and Password missing + --server mqtt.xxxxxxx.com --port 8883 --tls.
Now configured successfully.

**Comment by tve** [comment] 2020-07-02 06:15
Closing as a duplicate of #8

**Closed by tve** 2020-07-02 06:15 UTC
